<a href="https://colab.research.google.com/github/SahilKumar-003/Python_Tutor/blob/main/Numpy_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
num = np.array([5,6,3,5,8,62])
print(num)
print(num[0])
print(num[1:3])
print(num[-1])
print(num[-3:])

[ 5  6  3  5  8 62]
5
[6 3]
62
[ 5  8 62]


In [9]:
num2 = np.sort(num)      #sort
mean = np.mean(num)      #mean
print("Mean =",mean)
print(num2)


Mean = 14.833333333333334
[ 3  5  5  6  8 62]


**Broadcasting**

In [10]:
a = np.array([5,6,2,4,8,7])
b = np.array([5])
print(a+b)

[10 11  7  9 13 12]


In [11]:
a = np.array([5,6,2,8,9,5,6])
b = np.array([3,2,6,7,9,8,5])
c = a + b
print(c)

[ 8  8  8 15 18 13 11]


In [12]:
import pandas as pd
employee = {"name":["aryan","nitin","ravi"]
             ,"salary": [50000,45000,30000],
             "designation":["HR","DSE","SP"]}
df = pd.DataFrame(employee)
print(df)

    name  salary designation
0  aryan   50000          HR
1  nitin   45000         DSE
2   ravi   30000          SP


In [39]:
import matplotlib.pyplot as plt
df = pd.read_csv("sales.csv")
df.to_csv("new_sales.csv",index = False)
print(df)
#State Wise Sale
state_wise_sale = df.groupby("State")["Amount"].sum()   #plot(kind = "pie")
print(state_wise_sale)
# plt.show()
state_wise_sale.to_csv("state_wise_sale")
df = df.groupby(["State","Product"])["Amount"].sum() #.plot(kind = "bar",color = ["red","green","yellow","blue"])
df.to_csv("State_Product_wise_sale")
# plt.show()



     Customer Gender       State     Product  Amount
0       Alice      F  California      Laptop    1200
1         Bob      M       Texas       Phone     800
2     Charlie      M  California      Tablet     450
3       Diana      F    New York      Laptop    1300
4       Ethan      M       Texas  Headphones     200
5       Fiona      F     Florida       Phone     850
6      George      M  California       Phone     750
7      Hannah      F       Texas      Tablet     500
8         Ian      M     Florida      Laptop    1400
9        Jane      F    New York  Headphones     220
10      Kevin      M    New York      Laptop     976
11      Laura      F  California      Tablet    1186
12       Mike      M     Florida  Headphones     315
13       Nina      F  California      Laptop    1445
14      Oscar      F  California      Tablet     560
15      Paula      M       Texas  Headphones    1998
16      Quinn      M     Florida       Phone     526
17       Rita      F    New York      Tablet  

In [18]:
df = pd.read_csv("sales.csv")
df.head()

Customer Gender       State     Product  Amount
0    Alice      F  California      Laptop    1200
1      Bob      M       Texas       Phone     800
2  Charlie      M  California      Tablet     450
3    Diana      F    New York      Laptop    1300
4    Ethan      M       Texas  Headphones     200

In [17]:
df.tail()

Customer Gender       State     Product  Amount
45     Evelyn      F     Florida      Tablet    1434
46      Ethan      M       Texas      Laptop     664
47    Abigail      M    New York  Headphones    1419
48     Elijah      M    Illinois  Headphones    1508
49  Charlotte      F  California       Phone    1623

In [32]:
df.describe()

Amount
count    50.000000
mean   1069.260000
std     510.344294
min     200.000000
25%     666.250000
50%    1102.000000
75%    1442.250000
max    1998.000000

In [22]:
df.info()


<class 'pandas.core.series.Series'>
MultiIndex: 20 entries, ('California', 'Headphones') to ('Texas', 'Tablet')
Series name: Amount
Non-Null Count  Dtype
--------------  -----
20 non-null     int64
dtypes: int64(1)
memory usage: 538.0+ bytes


In [34]:
df = pd.read_csv("sales.csv")
df.columns

Index(['Customer', 'Gender', 'State', 'Product', 'Amount'], dtype='object')

In [38]:
df.dtypes

Customer    object
Gender      object
State       object
Product     object
Amount       int64
dtype: object

In [47]:
#EDA
employee = {"Name":["Akhil","Muskan","Raghav",None,"Akash",None],
            "Age":[20,21,None,23,None,20],
            "Designation":["HR","Manager","DSE","DSE","HR",None]}
df = pd.DataFrame(employee)
df.isnull().sum()   #Find No. of None Values

Name           2
Age            2
Designation    1
dtype: int64

In [46]:
#To find Values without ay None Values or values having all values
df.dropna()

Name   Age Designation
0   Akhil  20.0          HR
1  Muskan  21.0     Manager

In [48]:
# to Fill  None(empty space) values
df.fillna({"Name":"unknown","Age":df["Age"].mean(),"Designation":"Contract based"})

Name   Age     Designation
0    Akhil  20.0              HR
1   Muskan  21.0         Manager
2   Raghav  21.0             DSE
3  unknown  23.0             DSE
4    Akash  21.0              HR
5  unknown  20.0  Contract based

In [ ]:
# Kaggle.com (To find Dataset)